apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw-deployment
  namespace: asset
  labels:
    app: apigw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigw

  template:
    metadata:
      labels:
        app: apigw
    spec:
      containers:
        - name: apigw
#          image: samuelest/apigw:1.0-SNAPSHOT
          image: samuelest/apigw:6.5
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: azure
            - name: api-key-name
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: api-key-name
            - name: api-key-value
              valueFrom:
                secretKeyRef:
                  name: api-key-secret
                  key: api-key-value
          resources:
            requests:
              memory: 576Mi
      # nodeSelector:
      #   app: api-apps
   