namespace: asset-prod

asset:
  storageclass: asset-sc-prod
  pv: asset-pv-prod

  zookeeper:
    nodePort: 30182
  
  rabbitmq:
    nodePort:
      http: 31673
      amqp: 30673

  zipkin:
    ingress:
      host: asset-zipkin.az1-ahi-int.com
    memory: 576Mi

  apigw:
    image: samuelest/apigw:2.4
    memory: 576Mi
    ingress:
      host: asset-api.az1-ahi-int.com

  eureka:    
    image: samuelest/eureka-server:2.4
    memory: 576Mi

  security:    
    image: samuelest/api-security:2.4
    memory: 576Mi
    ingress:
      host: asset-api-auth.az1-ahi-int.com
      
  customers:    
    image: samuelest/api-customers:2.4
    memory: 576Mi
  
  fraud:    
    image: samuelest/api-fraud:2.4
    memory: 576Mi

  messages:    
    image: samuelest/api-messages:2.4
    memory: 576Mi

  notifications:
    memory: 576Mi
    image: samuelest/api-notifications:2.4
    
  users:
    image: samuelest/api-users:2.4
    memory: 576Mi
    dataSource:
      database: dGthaGlkYg==
      key: TTRWNXJXWHpBZFl2MFQzaDA2Y0JNSXQ0a0VmYlhNaTR2VWU0d2x4YjFUMlN0OTcybVA3YVpuOGNZcmV1ZkpWdG4wZXpCSHp4YWlsVEFDRGJJVDFQdWc9PQ==       
      uri: aHR0cHM6Ly9haGktYmhhLWNvc21vcy1kZXYuZG9jdW1lbnRzLmF6dXJlLmNvbTo0NDMv