namespace: asset-prod

asset:
  storageclass: asset-sc-prod
  pv: asset-pv-prod

  zookeeper:
    nodePort: 30182
  
  rabbitmq:
    nodePort:
      http: 31673
      amqp: 30673

  zipkin:
    ingress:
      host: asset-zipkin.az1-assets.com
    memory: 576Mi

  apigw:
    image: samuelest/apigw:2.5
    memory: 576Mi
    ingress:
      host: asset-api.az1-assets.com

  eureka:    
    image: samuelest/eureka-server:2.5
    memory: 576Mi

  security:    
    image: samuelest/api-security:2.5
    memory: 576Mi
    ingress:
      host: asset-api-auth.az1-assets.com
      
  customers:    
    image: samuelest/api-customers:2.5
    memory: 576Mi
  
  fraud:    
    image: samuelest/api-fraud:2.5
    memory: 576Mi

  messages:    
    image: samuelest/api-messages:2.5
    memory: 576Mi

  notifications:
    memory: 576Mi
    image: samuelest/api-notifications:2.5
    
  users:
    image: samuelest/api-users:2.5
    memory: 576Mi
    dataSource:
      database: YXNzZXQtZGVtbw==
      key: TUZnaXBJNnA5d2RLdExuZUxVUkpIMHV4Q1NYaExKMHV2ZjZNMzdFaUlXRjRTclI1RU1lWUVuQklZUXlpUlVTc21FNFJCTkJqWTl4ZUFDRGJ4WWtteHc9PQ==
      uri: aHR0cHM6Ly9hc3NldC5kb2N1bWVudHMuYXp1cmUuY29tOjQ0My8=