apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-customers
  namespace: asset
  labels:
    app: api-customers
spec:
  replicas: 1
  template:
    metadata:
      name: api-customers
      labels:
        app: api-customers
    spec:
      containers:
        - name: api-customer2
          image: samuelest/api-customers:6.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: azure
          resources:
            requests:
              memory: 576Mi              
      restartPolicy: Always
  selector:
    matchLabels:
      app: api-customers